logging:
  file:
    name: logs/app.log
  level:
    root: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n%ex"

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

  jackson:
    generator:
      escape-non-ascii: false